services:
  mysql:
    image: mysql:latest
    container_name: todolist-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: todolist
    ports:
      - "3306:3306"
    volumes:
      - todolist-mysql:/var/lib/mysql

  todolist:
    image:


volumes:
  todolist-mysql:
